### ISSUE TITLE
make fails at linking

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [clMathLibraries/clBLAS#122]
I'm trying to compile clblas on Debian, but fails at linking

https://gist.github.com/Alessandro-Barbieri/9a808ac4d2f65eb3402f#file-gistfile1-txt

**Comment by TimmyLiu** [comment]
I think your error message "riferimento non definito a "clEnqueueFillBuffer"" means "undefined reference to "clEnqueueFillBuffer" " in English?
clEnqueueFillBuffer is new in OpenCL 1.2 and later. Are you building with OpenCL 1.1?

**Comment by Alessandro-Barbieri** [comment]
Yes, is undefined reference and sadly I'm using libopencl1 340.65-2 from nvidia
and it states

> This package contains the ICD Loader library provided by NVIDIA. This library
> supports OpenCL 1.1 only.

**Comment by TimmyLiu** [comment]
I am afraid OpenCL 1.2 headers are required now. Looks later versions of Nvidia driver supports OpenCL 1.2. Refer to issue #117 for workaround if it still does not work for you.

**Comment by hughperkins** [comment]
Note that whilst I think that as an AMD project, it's fairly reasonable to use the latest versions of OpenCL, I reckon that it could be good to:
- point out in the release notes that the required version of OpenCL has been bumped
- point out the required version of OpenCL in a Requirements section (alongside Build Dependencies for example)
- notify in advance of release that the required version will be bumped

Of course, it will still stop working on devices that dont support 1.2, but at least it will be less surprising.

**Comment by TimmyLiu** [comment]
As indicated by issue #176 CUDA 7.5 now ships with OpenCL 1.2 header files. This issue can be closed.
